{
  "hash": "abbbf816c7da7f88a6328b020ede80bf",
  "result": {
    "markdown": "---\ntitle: \"Business task: Analyse product sales\"\ndate: 08/02/2023\nauthor: Reinout Schols \ncategories: [R, dplyr, analysis, business, visualization, ggplot]\nimage: \"histogrammen_groupen.png\"\ninclude: true\neditor: visual\nwarning: false\nmessage: false\nformat: \n  html:\n    code-fold: true\n    code-tools: true\n    highlight-style: github\n---\n\n\n# Certification - Data Analyst Professional - Product Sales {style=\"color:LightSteelBlue\"}\n\n<p style=\"color:white\">\n\nTo do:\n\n-   How many customers were there for each approach?\n\n-   What does the spread of the revenue look like overall? And for each method?\n\n-   Was there any difference in revenue over time for each of the methods?\n\n-   Based on the data,which method would you recommend we continue to use?\n\n-   Some of these methods take more time from the team so they may not be the best for us to use if the results are similar.\n\n</p>\n\n\n\n\n\n\n\n# Validating every column. {style=\"color:lightsteelblue\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking data types for the whole dataset.\n\nstr(ProductData)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t15000 obs. of  8 variables:\n $ week             : int  2 6 5 4 3 6 4 1 5 5 ...\n $ sales_method     : chr  \"Email\" \"Email + Call\" \"Call\" \"Email\" ...\n $ customer_id      : chr  \"2e72d641-95ac-497b-bbf8-4861764a7097\" \"3998a98d-70f5-44f7-942e-789bb8ad2fe7\" \"d1de9884-8059-4065-b10f-86eef57e4a44\" \"78aa75a4-ffeb-4817-b1d0-2f030783c5d7\" ...\n $ nb_sold          : int  10 15 11 11 9 13 11 10 11 11 ...\n $ revenue          : num  NA 225.5 52.5 NA 90.5 ...\n $ years_as_customer: int  0 1 6 3 0 10 9 1 10 7 ...\n $ nb_site_visits   : int  24 28 26 25 28 24 28 22 31 23 ...\n $ state            : chr  \"Arizona\" \"Kansas\" \"Wisconsin\" \"Indiana\" ...\n```\n:::\n\n```{.r .cell-code}\n# Counting rows in dataset\n         \nnrow(ProductData)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 15000\n```\n:::\n\n```{.r .cell-code}\n# Looking at unique values of the column sales_method (3 expected values).\n\nunique(ProductData$sales_method)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Email\"        \"Email + Call\" \"Call\"         \"em + call\"    \"email\"       \n```\n:::\n\n```{.r .cell-code}\n# Changing differences found the between groups.\n       \nProductData$sales_method[ProductData$sales_method == \"email\"] <- \"Email\"\n       \nProductData$sales_method[ProductData$sales_method == \"em + call\"] <- \"Email + Call\"\n         \n# Checking week column. (expected values: 1-6)\n       \nunique(ProductData$week)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2 6 5 4 3 1\n```\n:::\n\n```{.r .cell-code}\n# counting unique customers (checking if some customers are measured multiple times)\n        \nn_distinct(ProductData$customer_id)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 15000\n```\n:::\n\n```{.r .cell-code}\n# Checking new products sold column\n       \nunique(ProductData$nb_sold)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 10 15 11  9 13  8 12  7 14 16\n```\n:::\n\n```{.r .cell-code}\n# Counting NA's in revenue column\n         \nsum(is.na(ProductData$revenue))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1074\n```\n:::\n\n```{.r .cell-code}\n# Checking years as customers (company founded in 1984 so maximum amount of years should be 40 years)\n       \nunique(ProductData$years_as_customer)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  0  1  6  3 10  9  7  4  2 20  8  5 17 36 15 14 19 13 12 11 30 24 22 18 26\n[26] 23 32 16 39 25 33 21 31 27 34 28 29 35 38 37 63 47\n```\n:::\n\n```{.r .cell-code}\n# Checking number of times customer visited site in last 6 months.\n        \nunique(ProductData$nb_site_visits)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 24 28 26 25 22 31 23 30 21 27 32 29 20 18 19 35 16 17 33 36 34 15 37 14 13\n[26] 12 41\n```\n:::\n\n```{.r .cell-code}\n# Checking different states (50 states are expected)\n\nunique(ProductData$state)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Arizona\"        \"Kansas\"         \"Wisconsin\"      \"Indiana\"       \n [5] \"Illinois\"       \"Mississippi\"    \"Georgia\"        \"Oklahoma\"      \n [9] \"Massachusetts\"  \"Missouri\"       \"Texas\"          \"New York\"      \n[13] \"Maryland\"       \"California\"     \"Tennessee\"      \"Pennsylvania\"  \n[17] \"North Dakota\"   \"Florida\"        \"Michigan\"       \"North Carolina\"\n[21] \"Hawaii\"         \"Colorado\"       \"Louisiana\"      \"Virginia\"      \n[25] \"New Mexico\"     \"Arkansas\"       \"Alaska\"         \"Oregon\"        \n[29] \"New Hampshire\"  \"Ohio\"           \"New Jersey\"     \"Connecticut\"   \n[33] \"Iowa\"           \"Montana\"        \"Washington\"     \"Kentucky\"      \n[37] \"Alabama\"        \"Nebraska\"       \"South Carolina\" \"Minnesota\"     \n[41] \"South Dakota\"   \"Delaware\"       \"Maine\"          \"Utah\"          \n[45] \"West Virginia\"  \"Vermont\"        \"Rhode Island\"   \"Nevada\"        \n[49] \"Idaho\"          \"Wyoming\"       \n```\n:::\n\n```{.r .cell-code}\nn_distinct(ProductData$state)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 50\n```\n:::\n:::\n\n\n## Results of validating columns: {style=\"color:lightsteelblue\"}\n\n-   Sales_method: It had 5 values instead of the expected three groups. Therefore the spelling/data collection mistakes got changed to the expected three groups.\n\n-   week: expected weeks ranging from 1 to 6, this was found.\n\n-   customer_id: Counted the total amount of rows in the dataset, afterwards the unique values in the customer_id column got counted. We can conclude that each customer was only measured once.\n\n-   nb_sold: amount of numbers sold, only expectation was that it had to be a numeric. This was the case. Minimum was 7, maximum was 16.\n\n-   revenue: It had to be numeric and looking if there are any missing values. 1074 were found, these will be removed in the next step. The rest was ok.\n\n-   years_as_customer: Considering the company was launched in 1986, the expected maximum amount of years being a customer is 40. There were a couple of customers with values higher than 40. These are removed in the next step.\n\n-   nb_site_visits: It had to be numeric, besides that there was nothing unusual about the column.\n\n-   state: expected 50 unique states, this was the case.\n\n# Data cleaning {style=\"color:lightsteelblue\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Removing customers with an abnormal customer duration (longer than 40 years), assumed that the current year is 2023 AND removing rows with NA's.\n\nProductDataClean <- ProductData %>% filter(years_as_customer < 40) %>% na.omit(revenue)\n\n# Counting total amount of rows before and after cleaning\n\nProductData %>% count()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      n\n1 15000\n```\n:::\n\n```{.r .cell-code}\nProductDataClean %>% count()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      n\n1 13924\n```\n:::\n:::\n\n\n## Results of data cleaning: {style=\"color:lightsteelblue\"}\n\n-   2 customers were removed with a customer duration longer than 40 years.\n\n-   1074 customers had missing values in the revenue colmn\n\n-   A total of 1076 rows (customers) got removed.\n\n# Answering business questions {style=\"color:lightsteelblue\"}\n\n### How many customers were there for each approach? {style=\"color:white\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Counting the amount of customers for each approach before data cleaning\nProductData %>% group_by(sales_method) %>% count() %>% kable(caption = \"Amount of customers in each group before data cleaning\")\n```\n\n::: {.cell-output-display}\nTable: Amount of customers in each group before data cleaning\n\n|sales_method |    n|\n|:------------|----:|\n|Call         | 4962|\n|Email        | 7466|\n|Email + Call | 2572|\n:::\n\n```{.r .cell-code}\n# Counting the amount of customers for each approach after data cleaning\nProductDataClean %>% group_by(sales_method) %>% count() %>% kable(caption = \"Amount of customers in each group after data cleaning\")\n```\n\n::: {.cell-output-display}\nTable: Amount of customers in each group after data cleaning\n\n|sales_method |    n|\n|:------------|----:|\n|Call         | 4780|\n|Email        | 6921|\n|Email + Call | 2223|\n:::\n:::\n\n\n### Answer: {style=\"color:white\"}\n\n(after data cleaning) - Email: 6921 - Call: 4780 - Email + Call: 2223\n\n### What does the spread of the revenue look like overall? And for each method? {style=\"color:white\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Determining mean, median, range, min and max of the revenue.\n\nProductDataClean %>% summarise(mean_revenue = mean(revenue), sd_revenue = sd(revenue), median_revenue = median(revenue),  min_revenue = min(revenue), max_revenue = max(revenue), range_revenue = max(revenue) - min(revenue), Total_revenue = sum(revenue)) %>% arrange(desc(mean_revenue)) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  mean_revenue sd_revenue median_revenue min_revenue max_revenue range_revenue\n1     93.93783   47.43728           89.5       32.54      238.32        205.78\n  Total_revenue\n1       1307990\n```\n:::\n\n```{.r .cell-code}\n### Visualizing spread of revenue overall (graphics for a single variable)\n\n## Histogram\nggplot(ProductDataClean, aes(revenue)) + geom_histogram(binwidth = 18) + theme_classic()\n```\n\n::: {.cell-output-display}\n![](datacamp_index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\n## Boxplot\nggplot(ProductDataClean, aes(revenue)) + geom_boxplot() + theme_classic()\n```\n\n::: {.cell-output-display}\n![](datacamp_index_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Determining mean, median, range, min and max of the revenue for each group.\n\nProductDataClean %>% group_by(sales_method) %>% summarise(mean_revenue = mean(revenue),  sd_revenue = sd(revenue), median_revenue = median(revenue),  min_revenue = min(revenue), max_revenue = max(revenue), range_revenue = max(revenue) - min(revenue), Total_revenue = sum(revenue)) %>% arrange(desc(mean_revenue)) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 8\n  sales_method mean_revenue sd_revenue median_revenue min_revenue max_revenue\n  <chr>               <dbl>      <dbl>          <dbl>       <dbl>       <dbl>\n1 Email + Call        184.       29.1           185.        122.        238. \n2 Email                97.1      11.2            95.6        78.8       149. \n3 Call                 47.6       8.61           49.0        32.5        71.4\n# ℹ 2 more variables: range_revenue <dbl>, Total_revenue <dbl>\n```\n:::\n\n```{.r .cell-code}\n# Visualizing revenue for each group (graphics for multiple variables)\n\n## Histogram\nggplot(ProductDataClean, aes(revenue, color = sales_method)) + geom_histogram(binwidth = 5)  + theme_classic() \n```\n\n::: {.cell-output-display}\n![](datacamp_index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\n## Boxplot\nggplot(ProductDataClean, aes(revenue, color = sales_method)) + geom_boxplot()  + theme_classic()\n```\n\n::: {.cell-output-display}\n![](datacamp_index_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n:::\n\n\n### Answer {style=\"color:white\"}\n\n-   The average revenue over all weeks was 93,9378 for each customer, with a standard deviation of 47,4. 32,5 was the lowest revenue found, while the maximum was 328,3. The total revenue based on these new sale approaches was 1307990,32.\n\n-   Seperated in groups, Email + Call had the highest average revenue per customer. With also having the highest spread. In total revenue, calling performed best, Email + Call second best, and only calling had the lowest average and the lowest total revenue.\n\nConnecting numbers to visulisation:\n\nAt first glance the one variable histogram has three clear peaks, which hints at the three different groups. The histogram seperated for each group shows this underlying association.\n\n### Was there a difference in revenue over time for each of the methods? {style=\"color:white\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grouping data by sales method and the week.\n\nProductDataClean %>% group_by(sales_method, week) %>% summarise(mean_revenue = mean(revenue)) %>% arrange(desc(mean_revenue))  %>% \nkable(caption = \"Looking for week and group with best numbers\")\n```\n\n::: {.cell-output-display}\nTable: Looking for week and group with best numbers\n\n|sales_method | week| mean_revenue|\n|:------------|----:|------------:|\n|Email + Call |    6|    227.77064|\n|Email + Call |    5|    187.58834|\n|Email + Call |    4|    180.82263|\n|Email + Call |    2|    154.24696|\n|Email + Call |    3|    150.42327|\n|Email        |    6|    130.97652|\n|Email + Call |    1|    128.89565|\n|Email        |    5|    108.89231|\n|Email        |    4|    108.87714|\n|Email        |    2|    100.14124|\n|Email        |    3|     92.76257|\n|Email        |    1|     87.49640|\n|Call         |    6|     66.16609|\n|Call         |    5|     53.14609|\n|Call         |    4|     51.44706|\n|Call         |    2|     43.60261|\n|Call         |    3|     41.75953|\n|Call         |    1|     35.35024|\n:::\n\n```{.r .cell-code}\n# Line graph without fitting the line.\nggplot(ProductDataClean, aes(week, revenue, color = sales_method)) +\ngeom_line() + theme_classic() + geom_point()\n```\n\n::: {.cell-output-display}\n![](datacamp_index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Plotting line, best fit.\nggplot(ProductDataClean,\n                aes(\n                  week,\n                  revenue,\n                  colour = sales_method,\n                  fill = sales_method\n                )) +\n  geom_point(\n    size = 1,\n    alpha = 0.6,\n    position = position_jitter(width = 0.1, height = 0.1)\n  ) +\n  geom_smooth(method = \"lm\", alpha = 0.3)  +\n  scale_x_continuous(\n    breaks = c(0, 1, 2, 3, 4, 5, 6),\n    labels = c(\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\")\n  ) +\n  labs(\n    x = \"Weeks\",\n    y = \"Revenue\",\n    colour = \"Sales Method\",\n    fill = \"Sales Method\"\n  )   +\n  theme_minimal() \n```\n\n::: {.cell-output-display}\n![](datacamp_index_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n:::\n\n\n### Answer: {style=\"color:white\"}\n\nYes, there are clear differences in revenue over time. All three have a rising slope. Interesting to see that email + call and email differ significantly at week 1. Even though, according to the information, they started off with the same email.\n\nFor the rest it looks like email+call has the biggest rise in revenue over time. At week three and five there is a less steep slope for all three groups.\n\n### Differences between customers in groups: {style=\"color:white\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Average calculated for: revenue, years of being customer, products sold and site visits. Also grouped by sales method \n\nProductDataClean %>% group_by(sales_method) %>% summarise(mean_revenue = mean(revenue), mean_years_customer = mean(years_as_customer), mean_products_sold = mean(nb_sold), mean_site_visits = mean(nb_site_visits)) %>% \nkable(caption = \"Descriptices calculated for each group over the complete duration\")\n```\n\n::: {.cell-output-display}\nTable: Descriptices calculated for each group over the complete duration\n\n|sales_method | mean_revenue| mean_years_customer| mean_products_sold| mean_site_visits|\n|:------------|------------:|-------------------:|------------------:|----------------:|\n|Call         |     47.59687|            5.152720|           9.500837|         24.42176|\n|Email        |     97.12767|            4.989886|           9.723017|         24.73414|\n|Email + Call |    183.65123|            4.526316|          12.186685|         26.73864|\n:::\n\n```{.r .cell-code}\n# Average revenue for each group and each week, sorted descending\nProductDataClean %>% group_by(sales_method, week) %>% summarise(mean_revenue = mean(revenue)) %>% arrange(desc(mean_revenue))  %>% \nkable(caption = \"Looking for week and group with best numbers\")\n```\n\n::: {.cell-output-display}\nTable: Looking for week and group with best numbers\n\n|sales_method | week| mean_revenue|\n|:------------|----:|------------:|\n|Email + Call |    6|    227.77064|\n|Email + Call |    5|    187.58834|\n|Email + Call |    4|    180.82263|\n|Email + Call |    2|    154.24696|\n|Email + Call |    3|    150.42327|\n|Email        |    6|    130.97652|\n|Email + Call |    1|    128.89565|\n|Email        |    5|    108.89231|\n|Email        |    4|    108.87714|\n|Email        |    2|    100.14124|\n|Email        |    3|     92.76257|\n|Email        |    1|     87.49640|\n|Call         |    6|     66.16609|\n|Call         |    5|     53.14609|\n|Call         |    4|     51.44706|\n|Call         |    2|     43.60261|\n|Call         |    3|     41.75953|\n|Call         |    1|     35.35024|\n:::\n\n```{.r .cell-code}\n# Grouping by state and calculating average_revenue, arranged by descending revenue. Also showing the amount of customers in each group. \n groupedstates <- ProductDataClean %>% group_by(state) %>% summarise(mean_revenue = mean(revenue), count=n(), Total_revenue = sum(revenue)) %>% arrange(desc(Total_revenue))\ngroupedstates\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 50 × 4\n   state          mean_revenue count Total_revenue\n   <chr>                 <dbl> <int>         <dbl>\n 1 California             92.6  1737       160893.\n 2 Texas                  95.8  1109       106294.\n 3 New York               92.6   899        83243.\n 4 Florida                94.0   826        77652.\n 5 Illinois               91.4   576        52649.\n 6 Pennsylvania           93.3   553        51595.\n 7 Ohio                   92.3   520        48011.\n 8 Michigan               95.3   466        44425.\n 9 Georgia                94.4   460        43426.\n10 North Carolina         89.3   430        38418.\n# ℹ 40 more rows\n```\n:::\n\n```{.r .cell-code}\n# PLotting average revenue for each state\nggplot(groupedstates, aes(x=state,y= mean_revenue)) +\n  geom_segment( aes(x=state, xend=state, y=0, yend= mean_revenue), color=\"skyblue\") +\n  geom_point( color=\"blue\", size=0.5, alpha=0.6) +\n  theme_light() +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](datacamp_index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n### Answer {style=\"color:white\"}\n\n-   Email + call had the most products sold and the most site visits on average.\n-   California and Texas had the highest total revenue, while North and South Dakota had the highest average in revenue for each customer.\n\n### Based on the data, which method would you recommend we continue to use? Some of these methods take more time from the team so they may not be the best for us to use if the results are similar. {style=\"color:lightsteelblue\"}\n\n### Answer {style=\"color:white\"}\n\nBased on the information given: - Email: little effort and time - Call: 30 minutes per customer - Email + call: 10 minutes per customer\n\nThe conclusion is that calling is the least effective method, with an average revenue of 47,6. Between email only and email + call it is not completely clear yet. At first sight email + call performs better than only mail, with an average revenue per customer at 183.6512, compared to 91.1 in the email only group. However, there is no data given on the cost it takes to call each customer for 10 minutes, which probably has a big payroll cost.\n\nTherefore the advice is to track the exact time spent on each customer with details on how much this costs the company. This could lead to a better estimation of the best sales method. Further it could be usefull if the groups where completely randomized, and treated like a scientific experiment. This way statistical tests can be performed to improve the certainty of the results.\n\nWith the data given, I estimate the cost per minute for each group.\n\nTo estimate this I decided to use the next data found online: - Average salary in the USA for a sales representative: 30 dollars. (0.5 for each minute)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating metric for future references\n\nProductDataClean %>% group_by(sales_method) %>% summarise(mean_revenue = mean(revenue), nb_customers=n(), Total_revenue = sum(revenue)) %>% arrange(desc(mean_revenue))  %>% \nkable(caption = \"Average revenue, amount of customers, and total revenue\")\n```\n\n::: {.cell-output-display}\nTable: Average revenue, amount of customers, and total revenue\n\n|sales_method | mean_revenue| nb_customers| Total_revenue|\n|:------------|------------:|------------:|-------------:|\n|Email + Call |    183.65123|         2223|      408256.7|\n|Email        |     97.12767|         6921|      672220.6|\n|Call         |     47.59687|         4780|      227513.0|\n:::\n\n```{.r .cell-code}\n# 10 minutes (given time it took to call) + 1 minute for the email, times 50 cents  times number of customers.\n11 * 2223 * 0.5\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 12226.5\n```\n:::\n\n```{.r .cell-code}\n# 1 minute (estimation of time it took to send mails only) times 50 cents times number of customers\n1 * 0.5 * 6921\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3460.5\n```\n:::\n\n```{.r .cell-code}\n# 30 minutes times 50 cents times number of customers\n30 * 0.5 * 4780\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 71700\n```\n:::\n:::\n\n\n## Conclusion: {style=\"color:lightsteelblue\"}\n\nBased on these quick cost estimations, it appears that email + call is the best sales method to sell more products, this way we can enable our customers to be more creative, and improve their efficiency. Ofcourse this could be a big underestimation of the cost, but the graphs and data hint that email+calling is the best option. Calling only as a sales method should be avoided considering the cost and low returns.\n",
    "supporting": [
      "datacamp_index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}